name: ci

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            build-essential \
            cmake \
            libopengl-dev \
            libsdl2-dev \
            ninja-build

      - name: Create build environment
        # Hard cording the TUI build for now
        run: cmake -G Ninja -S . -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_APP_VERSION=TUI

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build/test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_folder
          path: |
            build/
            !build/**/*imgui*
            !build/**/*google*
            !build/**/*gmock*
            !build/**/*gtest*
        if: always()
