name: lint

on:
  push:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install clang-format

      - name: Run linter
        shell: bash
        run: |
          diff=$(bash -e scripts/apply-format)
          if [[ $diff ]]; then
            echo $diff
            exit 1
          fi
